name: Test

on: [push, pull_request]

jobs:
  test:
    if: ${{ github.repository != 'SpacelySprocketsInc/rachmari-test' || startsWith(github.ref, 'refs/heads/candidate-') }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
