on: push

jobs:

  hello_world_job:
    name: Hi there
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request' && github.event.action == 'unassigned'
        run: echo This event is an unassigned pull request.
