name: Greet Everyone
on: 
  workflow_dispatch:
    inputs:
      name:     
        description: 'entity to greet'
        required: true
        default: 'Mona the Octocat'  

jobs:
  hello_world_job:
    name: Hi there
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}!"
